export default function handler(req, res) {
  const { title } = req.query;
  const decodedTitle = decodeURIComponent(title);
  
  const parts = decodedTitle.split(" ");
  const titleJa = req.query.ja ? decodeURIComponent(req.query.ja) : decodedTitle;

  const svg = `<svg width="500" height="500" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" style="stop-color:#1a1a2e"/>
        <stop offset="100%" style="stop-color:#0f3460"/>
      </linearGradient>
    </defs>
    <rect width="500" height="500" fill="url(#bg)" rx="20"/>
    <rect x="10" y="10" width="480" height="480" fill="none" stroke="gold" stroke-width="3" rx="18"/>
    <text x="250" y="80" text-anchor="middle" font-family="sans-serif" font-size="40" fill="gold">Title Roulette</text>
    <text x="250" y="160" text-anchor="middle" font-family="sans-serif" font-size="28" font-weight="bold" fill="white">${parts[0] || ""}</text>
    <text x="250" y="220" text-anchor="middle" font-family="sans-serif" font-size="28" font-weight="bold" fill="white">${parts[1] || ""}</text>
    <text x="250" y="280" text-anchor="middle" font-family="sans-serif" font-size="28" font-weight="bold" fill="white">${parts[2] || ""}</text>
    <text x="250" y="360" text-anchor="middle" font-family="sans-serif" font-size="18" fill="rgba(255,215,0,0.8)">${titleJa}</text>
    <text x="250" y="440" text-anchor="middle" font-family="sans-serif" font-size="14" fill="rgba(255,255,255,0.4)">Base Chain NFT</text>
  </svg>`;

  const svgBase64 = Buffer.from(svg).toString("base64");
  const imageUri = "data:image/svg+xml;base64," + svgBase64;

  const metadata = {
    name: decodedTitle,
    description: "A legendary title from Title Roulette. Generated by birthday seed on Base chain.",
    image: imageUri,
    attributes: [
      { trait_type: "Adjective", value: parts[0] || "" },
      { trait_type: "Title", value: parts[1] || "" },
      { trait_type: "Trait", value: parts[2] || "" },
    ],
  };

  res.setHeader("Content-Type", "application/json");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.status(200).json(metadata);
}
